stages:
  data_ingestion:
    cmd: python main.py --stage data_ingestion
    deps:
      - src/WattPredictor/pipeline/stage01_ingestion.py
      - config_file/config.yaml
    outs:
      - data/processed

  data_validation:
    cmd: python main.py --stage data_validation
    deps:
      - src/WattPredictor/pipeline/stage02_validation.py
      - data/processed/elec_wx_demand.csv
      - config_file/config.yaml
      - config_file/schema.yaml
    outs:
      - artifacts/data_validation/status.json

  data_transformation:
    cmd: python main.py --stage data_transformation
    deps:
      - src/WattPredictor/pipeline/stage03_transformation.py
      - config_file/config.yaml
      - config_file/schema.yaml
      - config_file/params.yaml
      - artifacts/data_validation/status.json
    outs:
      - artifacts/data_transformation/label_encoder.pkl

  model_trainer:
    cmd: python main.py --stage model_training
    deps:
      - src/WattPredictor/pipeline/stage04_trainer.py
      - config_file/config.yaml
      - config_file/params.yaml

    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python main.py --stage model_evaluation
    deps:
      - src/WattPredictor/pipeline/stage05_evaluation.py
      - config_file/config.yaml
      - config_file/params.yaml
      - artifacts/model_trainer/model.joblib
    outs:
      - artifacts/model_evaluation/metrics.json

