stages:
  feature_pipeline:
    cmd: python main.py --stage feature_pipeline
    deps:
      - src/WattPredictor/pipeline/feature_pipeline.py
      - config_file/config.yaml
      - config_file/params.yaml
      - config_file/schema.yaml
    outs:
      - dataset/processed/elec_wx_demand.csv
      - artifacts/engineering/label_encoder.pkl

  training_pipeline:
    cmd: python main.py --stage training_pipeline
    deps:
      - src/WattPredictor/pipeline/training_pipeline.py
      - dataset/processed/elec_wx_demand.csv
      - artifacts/engineering/label_encoder.pkl
      - config_file/config.yaml
      - config_file/params.yaml
      - config_file/schema.yaml
    outs:
      - artifacts/trainer/model.joblib

  inference_pipeline:
    cmd: python main.py --stage inference_pipeline
    deps:
      - src/WattPredictor/pipeline/inference_pipeline.py
      - artifacts/trainer/model.joblib
      - config_file/config.yaml
      - config_file/params.yaml
      - config_file/schema.yaml
    outs:
      - artifacts/prediction/predictions.csv

  monitoring_pipeline:
    cmd: python main.py --stage monitoring_pipeline
    deps:
      - src/WattPredictor/pipeline/monitoring_pipeline.py
      - artifacts/prediction/predictions.csv
      - config_file/config.yaml
      - config_file/params.yaml
      - config_file/schema.yaml
    outs:
      - artifacts/monitoring/monitoring_df.csv
      - artifacts/drift/

