stages:
  prepare_data:
    cmd: python src/WattPredictor/pipeline/feature_pipeline.py
    deps:
      - src/WattPredictor/components/features/
      - src/WattPredictor/config/config.py
    outs:
      - data/processed/elec_wx_demand.csv:
          cache: true
      - artifacts/engineering/preprocessed.csv:
          cache: true
    desc: "Ingest data from APIs and engineer time-series features"

  train_model:
    cmd: python src/WattPredictor/pipeline/training_pipeline.py
    deps:
      - src/WattPredictor/config/config.py
      - src/WattPredictor/components/training/
      - src/WattPredictor/components/monitor/drift.py
      - src/WattPredictor/utils/ts_generator.py
      - artifacts/engineering/preprocessed.csv
    params:
      - config_file/params.yaml:
          - training.input_seq_len
          - training.cv_folds
    outs:
      - artifacts/trainer/model.joblib:
          cache: true
      - artifacts/drift/:
          cache: false
    metrics:
      - artifacts/evaluation/metrics.json:
          cache: false
      - artifacts/evaluation/business_impact.json:
          cache: false
    desc: "Train best model with grid search + Evidently drift monitoring"

  predict:
    cmd: python src/WattPredictor/pipeline/inference_pipeline.py
    deps:
      - src/WattPredictor/config/config.py
      - artifacts/trainer/model.joblib
    outs:
      - artifacts/prediction/predictions.csv:
          cache: true
    desc: "Generate predictions for deployment"


