stages:
  data_ingestion:
    cmd: python main.py --stage data_ingestion
    deps:
      - src/WattPredictor/pipeline/stage01_ingestion.py
      - config_file/config.yaml
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python main.py --stage data_validation
    deps:
      - src/WattPredictor/pipeline/stage02_validation.py
      - artifacts/data_ingestion/data/elec_wx_demand.csv
      - config_file/config.yaml
      - config_file/schema.yaml
    outs:
      - artifacts/data_validation/status.json

  data_transformation:
    cmd: python main.py --stage data_transformation
    deps:
      - src/WattPredictor/pipeline/stage03_transformation.py
      - config_file/config.yaml
      - config_file/schema.yaml
      - config_file/params.yaml
      - artifacts/data_validation/status.json
    outs:
      - artifacts/data_transformation/label_encoder.pkl
      - artifacts/data_transformation/x_transform.npy
      - artifacts/data_transformation/y_transform.npy
      - artifacts/data_transformation/train_features.csv
      - artifacts/data_transformation/test_features.csv
      - artifacts/data_transformation/train_target.csv
      - artifacts/data_transformation/test_target.csv

  model_trainer:
    cmd: python main.py --stage model_training
    deps:
      - src/WattPredictor/pipeline/stage04_trainer.py
      - config_file/config.yaml
      - config_file/params.yaml
      - artifacts/data_transformation/x_transform.npy
      - artifacts/data_transformation/y_transform.npy

    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python main.py --stage model_evaluation
    deps:
      - src/WattPredictor/pipeline/stage05_evaluation.py
      - config_file/config.yaml
      - config_file/params.yaml
      - artifacts/model_trainer/model.joblib
      - artifacts/data_transformation/x_transform.npy
      - artifacts/data_transformation/y_transform.npy
    outs:
      - artifacts/model_evaluation/metrics.json

