services:
  - type: web
    name: wattpredictor
    runtime: docker
    plan: free
    repo: https://github.com/JavithNaseem-J/WattPredictor
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    autoDeployTrigger: 'off'
    envVars:
      - key: ELEC_API_KEY
        sync: false
      - key: ELEC_API
        value: https://api.eia.gov/v2/
      - key: WX_API
        value: https://archive-api.open-meteo.com/v1/archive
