services:
  - type: web
    name: wattpredictor-dashboard
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    autoDeploy: false
    envVars:
      - key: ELEC_API_KEY
        sync: false
      - key: ELEC_API
        value: https://api.eia.gov/v2/
      - key: WX_API
        value: https://archive-api.open-meteo.com/v1/archive
