dates:
  start_date: "2025-01-01"
  end_date: "2025-05-30"

  
training:
  scoring: neg_root_mean_squared_error
  cv_folds: 5
  n_jobs: -1
  n_trials: 5
  input_seq_len: 672
  step_size: 6
  cutoff_date: '2025-03-15T00:00:00'


