training:
  cv_folds: 5
  n_jobs: -1
  n_trials: 7
  input_seq_len: 672
  step_size: 23


monitoring:
  from_date: "2025-03-17 00:00:00"
  to_date: "2025-03-17 23:59:59"

drift:
  baseline_start: "2024-07-17"
  baseline_end: "2025-02-28"
  current_start: "2025-03-18"
  current_end: "2025-07-17"

  

