dates:
  start_date: "2025-01-01"
  end_date: "2025-03-30"


transformation:
  input_seq_len: 672
  step_size: 6
  cutoff_date: '2025-03-05T00:00:00'

model_trainer:
  scoring: neg_root_mean_squared_error
  cv_folds: 5
  n_jobs: -1
  n_trials: 1
  early_stopping_rounds: 10


