columns:
  period: object
  subba: object
  subba_name: object
  parent: object
  parent_name: object
  value: int64
  value_units: object
  date: object
  temperature_2m: float64
  weather_code: float64
  relative_humidity_2m: float64
  wind_speed_10m: float64